### ISSUE TITLE
plot_monthly.py crashing

### ISSUE THREAD

**Issue by initze** [initze/noaaplotter#1]
python plot_monthly.py -infile ./data/alaska.csv -loc Kotzebue -start 1990-01-01 -end 2017-11-30 -type Temperature -trail 12 -plot -anomaly
Traceback (most recent call last):
  File "plot_monthly.py", line 72, in <module>
    main()
  File "plot_monthly.py", line 69, in main
    save_path=args.save_path)
  File "C:\Users\initze\Documents\Python_Scripts\noaaplotter-0.1.6\noaaplotter\noaaplotter.py", line 323, in plot_monthly_barchart
    data_clim = self.dataset.get_monthy_climate(self.df_clim_)
  File "C:\Users\initze\Documents\Python_Scripts\noaaplotter-0.1.6\noaaplotter\dataset.py", line 139, in get_monthy_climate
    df['Month'] = df.apply(lambda x: parse_dates_YM(x['DATE_YM']).month, axis=1)
AttributeError: 'NOAAPlotterDailyClimateDataset' object has no attribute 'apply'

**Comment by initze** [comment]
fixed with 0.1.7
