### ISSUE TITLE
crash daily plot

### ISSUE THREAD

**Issue by initze** [initze/noaaplotter#17]
> (noaaplotter) C:\Users\initze\Documents\Python Scripts\noaaplotter>python plot_daily.py -infile data/kotzebue.csv -start 1992-01-01 -end 1992-12-31 -t_range -45 25 -p_range 50
> C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\cbook\__init__.py:1402: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
>   x[:, None]
> C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\axes\_base.py:276: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
>   x = x[:, np.newaxis]
> C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\axes\_base.py:278: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
>   y = y[:, np.newaxis]
> Traceback (most recent call last):
>   File "plot_daily.py", line 97, in <module>
>     main()
>   File "plot_daily.py", line 94, in main
>     figsize=args.figsize)
>   File "C:\Users\initze\Documents\Python Scripts\noaaplotter\noaaplotter\noaaplotter.py", line 277, in plot_weather_series
>     bbox_to_anchor=(0.5, -0.2))
>   File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\axes\_axes.py", line 406, in legend
>     self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
>   File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\legend.py", line 575, in __init__
>     self._init_legend_box(handles, labels, markerfirst)
>   File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\legend.py", line 833, in _init_legend_box
>     fontsize, handlebox))
>   File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\legend_handler.py", line 115, in legend_artist
>     fontsize, handlebox.get_transform())
>   File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\legend_handler.py", line 299, in create_artists
>     self.update_prop(p, orig_handle, legend)
>   File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\legend_handler.py", line 72, in update_prop
>     self._update_prop(legend_handle, orig_handle)
>   File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\legend_handler.py", line 65, in _update_prop
>     self._update_prop_func(legend_handle, orig_handle)
>   File "C:\Users\initze\AppData\Local\Continuum\anaconda3\envs\noaaplotter\lib\site-packages\matplotlib\legend_handler.py", line 38, in update_from_first_child
>     tgt.update_from(src.get_children()[0])
> IndexError: list index out of range

**Comment by initze** [comment]
fixed with f355fc9f1191626de6260d60aec76623d16dae76
