### ISSUE TITLE
crash when dates go beyond dataset

### ISSUE THREAD

**Issue by initze** [initze/noaaplotter#3]
>python plot_monthly.py -infile ./data/alaska.csv -loc Fairbanks -start 1990-01-01 -end 2020-12-31 -type Temperature -trail 12 -plot -anomaly
Traceback (most recent call last):
  File "plot_monthly.py", line 72, in <module>
    main()
  File "plot_monthly.py", line 69, in main
    save_path=args.save_path)
  File "C:\Users\initze\OneDrive\noaaplotter\noaaplotter\noaaplotter\noaaplotter.py", line 329, in plot_monthly_barchart
    data_monthly = DS_monthly(self.dataset, start=start_date, end=end_date)
  File "C:\Users\initze\OneDrive\noaaplotter\noaaplotter\noaaplotter\dataset.py", line 256, in __init__
    self._validate_date_range()
  File "C:\Users\initze\OneDrive\noaaplotter\noaaplotter\noaaplotter\dataset.py", line 263, in _validate_date_range
    raise ('Dataset is insufficient to calculate climate normals!')
TypeError: exceptions must derive from BaseException

**Comment by initze** [comment]
fixed with bdda08204b3181d277e1d33f9c28e29eb96a174a
